lib/notify_events_web/router.ex
defmodule NotifyEventsWeb.Router do
  use NotifyEventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug NotifyEvents.Accounts.Session
  end

  scope "/", NotifyEventsWeb do
    pipe_through :browser
    pipe_through :with_session

    get "/", BulletinController, :index

    # resources "/subscribers", SubscriberController
    resources "/users", UserController, only: [:show, :edit, :new, :create, :update]
    resources "/boards", BulletinController

    resources "/events", EventController, only: [:edit, :update, :delete]
    get "/boards/:bulletin_id/new_event", EventController, :new
    post "/boards/:bulletin_id/new_event", EventController, :create

    get "/boards/:bulletin_id/notifications", NotificationController, :index
    get "/boards/:bulletin_id/new_notification", NotificationController, :new
    post "/boards/:bulletin_id/new_notification", NotificationController, :create

    # resources "/notifications", NotificationController

    get "/signin/:token", SessionController, :show, as: :signin
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", NotifyEventsWeb do
    pipe_through :browser_api

    post "/subscribers", SubscriberController, :create
    delete "/subscribers", SubscriberController, :delete
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotifyEventsWeb.Telemetry
    end
  end
end

lib/notify_events/board/subscriber.ex
defmodule NotifyEvents.Board.Subscriber do
  use Ecto.Schema
  import Ecto.Changeset

  schema "subscribers" do
    field :ip_addr, :string
    field :name, :string
    field :pn_auth, :string
    field :pn_endpoint, :string
    field :pn_p256dh, :string
    field :user_agent, :string

    belongs_to :bulletin, Bulletin

    timestamps()
  end

  @doc false
  def changeset(subscriber, attrs) do
    subscriber
    |> cast(attrs, [
      :name,
      :pn_endpoint,
      :pn_p256dh,
      :pn_auth,
      :ip_addr,
      :user_agent,
      :bulletin_id
    ])
    |> validate_required([:pn_endpoint, :pn_p256dh, :pn_auth, :ip_addr, :user_agent, :bulletin_id])
  end
end

lib/notify_events_web/controllers/subscriber_controller.ex
defmodule NotifyEventsWeb.SubscriberController do
  use NotifyEventsWeb, :controller

  alias NotifyEvents.Board
  alias NotifyEvents.Board.Subscriber

  def create(conn, %{"subscriber" => subscriber_params}) do
    subscriber_params =
      Map.merge(subscriber_params, %{
        "ip_addr" => to_string(:inet_parse.ntoa(conn.remote_ip)),
        "user_agent" => get_req_header(conn, "user-agent") |> Enum.at(0)
      })

    case Board.create_subscriber(subscriber_params) do
      {:ok, _subsriber} ->
        conn
        |> send_resp(200, "")

      {:error, _changeset} ->
        conn
        |> send_resp(400, "")
    end
  end

  def delete(conn, %{"subscriber" => subscriber_params}) do
    subscriber =
      Board.get_subscriber_by_endpoint_bulletin(
        subscriber_params["endpoint"],
        subscriber_params["bulletin_id"]
      )

    if subscriber do
      Board.delete_subscriber(subscriber)
    end

    conn
    |> send_resp(200, "")
  end
end

lib/notify_events_web/views/subscriber_view.ex
defmodule NotifyEventsWeb.SubscriberView do
  use NotifyEventsWeb, :view
end

lib/notify_events_web/templates/subscriber/edit.html.eex
<h1>Edit Subscriber</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.subscriber_path(@conn, :update, @subscriber)) %>

<span><%= link "Back", to: Routes.subscriber_path(@conn, :index) %></span>

lib/notify_events_web/templates/subscriber/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :pn_endpoint %>
  <%= text_input f, :pn_endpoint %>
  <%= error_tag f, :pn_endpoint %>

  <%= label f, :pn_p256dh %>
  <%= text_input f, :pn_p256dh %>
  <%= error_tag f, :pn_p256dh %>

  <%= label f, :pn_auth %>
  <%= text_input f, :pn_auth %>
  <%= error_tag f, :pn_auth %>

  <%= label f, :ip_addr %>
  <%= text_input f, :ip_addr %>
  <%= error_tag f, :ip_addr %>

  <%= label f, :user_agent %>
  <%= text_input f, :user_agent %>
  <%= error_tag f, :user_agent %>

  <div>
    <%= submit "Save", class: "rounded-md m-2 bg-blue-100 p-2 text-sm text-blue-700" %>
  </div>
<% end %>

lib/notify_events_web/templates/subscriber/index.html.eex
<h1>Listing Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pn endpoint</th>
      <th>Pn p256dh</th>
      <th>Pn auth</th>
      <th>Ip addr</th>
      <th>User agent</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for subscriber <- @subscribers do %>
    <tr>
      <td><%= subscriber.name %></td>
      <td><%= subscriber.pn_endpoint %></td>
      <td><%= subscriber.pn_p256dh %></td>
      <td><%= subscriber.pn_auth %></td>
      <td><%= subscriber.ip_addr %></td>
      <td><%= subscriber.user_agent %></td>

      <td>
        <span><%= link "Show", to: Routes.subscriber_path(@conn, :show, subscriber) %></span>
        <span><%= link "Edit", to: Routes.subscriber_path(@conn, :edit, subscriber) %></span>
        <span><%= link "Delete", to: Routes.subscriber_path(@conn, :delete, subscriber), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Subscriber", to: Routes.subscriber_path(@conn, :new) %></span>

lib/notify_events_web/templates/subscriber/new.html.eex
<h1>New Subscriber</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.subscriber_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.subscriber_path(@conn, :index) %></span>

lib/notify_events_web/templates/subscriber/show.html.eex
<h1>Show Subscriber</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @subscriber.name %>
  </li>

  <li>
    <strong>Pn endpoint:</strong>
    <%= @subscriber.pn_endpoint %>
  </li>

  <li>
    <strong>Pn p256dh:</strong>
    <%= @subscriber.pn_p256dh %>
  </li>

  <li>
    <strong>Pn auth:</strong>
    <%= @subscriber.pn_auth %>
  </li>

  <li>
    <strong>Ip addr:</strong>
    <%= @subscriber.ip_addr %>
  </li>

  <li>
    <strong>User agent:</strong>
    <%= @subscriber.user_agent %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.subscriber_path(@conn, :edit, @subscriber) %></span>
<span><%= link "Back", to: Routes.subscriber_path(@conn, :index) %></span>