lib/notify_events_web/router.ex
defmodule NotifyEventsWeb.Router do
  use NotifyEventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug NotifyEvents.Accounts.Session
  end

  scope "/", NotifyEventsWeb do
    pipe_through :browser
    pipe_through :with_session

    get "/", BulletinController, :index

    # resources "/subscribers", SubscriberController
    resources "/users", UserController, only: [:show, :edit, :new, :create, :update]
    resources "/boards", BulletinController

    resources "/events", EventController, only: [:edit, :update, :delete]
    get "/boards/:bulletin_id/new_event", EventController, :new
    post "/boards/:bulletin_id/new_event", EventController, :create

    get "/boards/:bulletin_id/notifications", NotificationController, :index
    get "/boards/:bulletin_id/new_notification", NotificationController, :new
    post "/boards/:bulletin_id/new_notification", NotificationController, :create

    # resources "/notifications", NotificationController

    get "/signin/:token", SessionController, :show, as: :signin
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", NotifyEventsWeb do
    pipe_through :browser_api

    post "/subscribers", SubscriberController, :create
    delete "/subscribers", SubscriberController, :delete
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotifyEventsWeb.Telemetry
    end
  end
end

lib/notify_events_web/views/layout_view.ex
defmodule NotifyEventsWeb.LayoutView do
  use NotifyEventsWeb, :view
end

lib/notify_events_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>NotifyEvents</title>
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/site.webmanifest") %>">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="m-2">
    <header class="w-full border-b-2 border-gray-100 mb-6">
      <section class="max-w-7xl px-6 w-full my-0 mx-auto relative flex flex-col md:flex-row justify-between items-center">
        <a href="/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/banner.png") %>" alt="Phoenix Framework Logo"/>
        </a>
        <nav role="navigation">
          <ul>
          <%= if @current_user do %>
            <%= link @current_user.name, to: Routes.user_path(@conn, :show, @current_user.id) %>
            <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete%>
          <% else %>
            <li><%= link "Sign In", to: Routes.session_path(@conn, :new) %></li>
            <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
          <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="max-w-7xl py-0 px-2 md:px-8 my-0 mx-auto w-full relative">
      <%= if info = get_flash(@conn, :info) do %>
        <div class="rounded-md mb-4 bg-blue-100 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3 flex-1 md:flex md:justify-between">
              <p class="text-sm text-blue-700" role="alert">
                <%= info %>
              </p>
            </div>
          </div>
        </div>
      <% end %>

      <%= if error = get_flash(@conn, :error) do %>
        <div class="rounded-md mb-4 bg-red-100 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3 flex-1 md:flex md:justify-between">
              <p class="text-sm text-red-700" role="alert">
                <%= error %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/notify_events_web/templates/layout/bulletin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= @bulletin.title %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script>pn_serverkey = "<%= System.get_env("WEB_PUSH_PUBLIC") %>"; bulletin_id="<%= @bulletin.id %>"; csrf_token="<%= Plug.CSRFProtection.get_csrf_token() %>"</script>
  </head>
  <body class="bg-yellow-50 flex flex-col min-h-screen">
    <header class="bg-yellow-100">
        <nav class="flex items-center justify-between container p-6 mx-auto">
            <h1 class="text-xl font-bold sm:text-4xl">
                <%= @bulletin.title %>: by&nbsp<%= link @bulletin.user.name, to: Routes.user_path(@conn, :show, @bulletin.user) %>
            </h1>
            <a id="sub_btn" href="#" class="p-2 sm:px-6 bg-teal-500 hover:bg-teal-600 rounded-md text-white sm:text-lg">loading...</a>
        </nav>
    </header>
    <main class="container mx-auto flex-grow">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner_content %>

    </main>

    <footer class="container mx-auto">
      <nav role="navigation" class="px-2 my-7 text-gray-600 flex space-x-4 justify-between">
        <p>
        <%= link "Home", to: Routes.bulletin_path(@conn, :index), class: "text-lg rounded-md m-2 bg-yellow-100 p-2 text-sm text-gray-700"%>
        </p>

        <p>
        <%= if @current_user do %>
            <%= link @current_user.name, to: Routes.user_path(@conn, :show, @current_user.id), class: "text-lg rounded-md m-2 bg-yellow-100 p-2 text-sm text-gray-700"%>
            <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "text-lg rounded-md m-2 bg-gray-100 p-2 text-sm text-gray-700"%>
        <% else %>
            <%= link "Sign In", to: Routes.session_path(@conn, :new), class: "text-lg rounded-md m-2 bg-yellow-100 p-2 text-sm text-gray-700" %>
            <%= link "Register", to: Routes.user_path(@conn, :new), class: "text-lg rounded-md m-2 bg-gray-100 p-2 text-sm text-gray-700" %>
        <% end %>
        </p>
      </nav>
    </footer>

  </body>
</html>