lib/notify_events_web/router.ex
defmodule NotifyEventsWeb.Router do
  use NotifyEventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug NotifyEvents.Accounts.Session
  end

  scope "/", NotifyEventsWeb do
    pipe_through :browser
    pipe_through :with_session

    get "/", BulletinController, :index

    # resources "/subscribers", SubscriberController
    resources "/users", UserController, only: [:show, :edit, :new, :create, :update]
    resources "/boards", BulletinController

    resources "/events", EventController, only: [:edit, :update, :delete]
    get "/boards/:bulletin_id/new_event", EventController, :new
    post "/boards/:bulletin_id/new_event", EventController, :create

    get "/boards/:bulletin_id/notifications", NotificationController, :index
    get "/boards/:bulletin_id/new_notification", NotificationController, :new
    post "/boards/:bulletin_id/new_notification", NotificationController, :create

    # resources "/notifications", NotificationController

    get "/signin/:token", SessionController, :show, as: :signin
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", NotifyEventsWeb do
    pipe_through :browser_api

    post "/subscribers", SubscriberController, :create
    delete "/subscribers", SubscriberController, :delete
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotifyEventsWeb.Telemetry
    end
  end
end

lib/notify_events/board/bulletin.ex
defmodule NotifyEvents.Board.Bulletin do
  use Ecto.Schema
  import Ecto.Changeset

  alias NotifyEvents.Board

  schema "bulletins" do
    field :title, :string

    has_many :subscribers, Board.Subscriber
    has_many :events, Board.Event
    has_many :notifications, Board.Notification

    belongs_to :user, NotifyEvents.Accounts.User


    timestamps()
  end

  @doc false
  def changeset(bulletin, attrs) do
    bulletin
    |> cast(attrs, [:title, :user_id])
    |> validate_required([:title, :user_id])
  end
end

lib/notify_events_web/controllers/bulletin_controller.ex
defmodule NotifyEventsWeb.BulletinController do
  use NotifyEventsWeb, :controller

  alias NotifyEvents.Board
  alias NotifyEvents.Board.Bulletin

  plug :authenticate_user when action not in [:index, :show]
  plug :authorize_user when action in [:edit, :update, :delete]

  def index(conn, _params) do
    bulletins = Board.list_bulletins()
    render(conn, "index.html", bulletins: bulletins)
  end

  def new(conn, _params) do
    changeset = Board.change_bulletin(%Bulletin{})
    render(conn, "new.html", changeset: changeset, user: conn.assigns[:current_user])
  end

  def create(conn, %{"bulletin" => bulletin_params}) do
    bulletin_params = Map.merge(bulletin_params, %{"user_id" => conn.assigns[:current_user].id})

    case Board.create_bulletin(bulletin_params) do
      {:ok, bulletin} ->
        conn
        |> put_flash(:info, "Bulletin created successfully.")
        |> redirect(to: Routes.bulletin_path(conn, :show, bulletin))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    bulletin = Board.get_bulletin!(id)
    events = Board.list_events_by_bulletin(id)
    conn = put_layout(conn, "bulletin.html")
    render(conn, "show_app.html", bulletin: bulletin, events: events)
  end

  def edit(conn, %{"id" => id}) do
    bulletin = Board.get_bulletin!(id)
    changeset = Board.change_bulletin(bulletin)
    render(conn, "edit.html", bulletin: bulletin, changeset: changeset)
  end

  def update(conn, %{"id" => id, "bulletin" => bulletin_params}) do
    bulletin = Board.get_bulletin!(id)

    bulletin_params = Map.merge(bulletin_params, %{"user_id" => conn.assigns[:current_user].id})

    case Board.update_bulletin(bulletin, bulletin_params) do
      {:ok, bulletin} ->
        conn
        |> put_flash(:info, "Bulletin updated successfully.")
        |> redirect(to: Routes.bulletin_path(conn, :show, bulletin))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", bulletin: bulletin, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    bulletin = Board.get_bulletin!(id)
    {:ok, _bulletin} = Board.delete_bulletin(bulletin)

    conn
    |> put_flash(:info, "Bulletin deleted successfully.")
    |> redirect(to: Routes.bulletin_path(conn, :index))
  end

  defp authenticate_user(conn, _params) do
    if conn.assigns.current_user != nil do
      conn
    else
      conn
      |> put_flash(:error, "You need to be signed in to do that!")
      |> redirect(to: Routes.session_path(conn, :new))
      |> halt()
    end
  end

  defp authorize_user(conn, _params) do
    %{params: %{"id" => bulletin_id}} = conn
    bulletin = Board.get_bulletin!(bulletin_id)

    if conn.assigns.current_user.id == bulletin.user_id do
      conn
    else
      conn
      |> put_flash(:error, "You are not the owner of this bulletin!")
      |> redirect(to: Routes.bulletin_path(conn, :show, bulletin_id))
      |> halt()
    end
  end
end

lib/notify_events_web/views/bulletin_view.ex
defmodule NotifyEventsWeb.BulletinView do
  use NotifyEventsWeb, :view
end

lib/notify_events_web/templates/bulletin/edit.html.eex
<h1>Edit Bulletin</h1>
<%= render "form.html", Map.put(assigns, :action, Routes.bulletin_path(@conn, :update, @bulletin)) %>

lib/notify_events_web/templates/bulletin/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
<%= label f, :title %>
<%= text_input f, :title %>
<%= error_tag f, :title %>
<%# <%= label f, :user_id %>
<%# <%= number_input f, :user_id %>
<%# <%= error_tag f, :user_id %>
<div class="flex justify-end m-2">
  <%= link "Back", to: Routes.bulletin_path(@conn, :index), class: "rounded-md m-2 bg-gray-100 p-2 text-sm text-gray-700" %>
  <%= submit "Save", class: "rounded-md m-2 bg-blue-100 p-2 text-sm text-blue-700" %>
</div>
<% end %>

lib/notify_events_web/templates/bulletin/index.html.eex
<div class="flex-col justify-center space-y-4 my-4 m-2">
<%= for bulletin <- Enum.sort(@bulletins, &(length(&1.subscribers) >= length(&2.subscribers))) do %>
    <%= link to: Routes.bulletin_path(@conn, :show, bulletin) do %>
      <div class="p-2 border-2 m-4 rounded-md mx-auto">
        <h1 class="text-xl font-semibold"><%= bulletin.title %></h1>
        <p>
          by <%= bulletin.user.name %>
          (<%= length bulletin.subscribers %> subscriber<%= if length(bulletin.subscribers) != 1 do "s" end %>)
        </p>
      </div>
  <% end %>
<% end %>
    <%= if @current_user do %>
    <span class="text-gray-600"><%= link "(Create New Bulletin)", to: Routes.bulletin_path(@conn, :new) %></span>
    <% end %>
</div>

lib/notify_events_web/templates/bulletin/new.html.eex
<h1>New Bulletin</h1>
<%= render "form.html", Map.put(assigns, :action, Routes.bulletin_path(@conn, :create)) %>

lib/notify_events_web/templates/bulletin/show.html.eex
<h1>Show Bulletin</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @bulletin.title %>
  </li>

  <li>
    <strong>Owner:</strong>
    <%= link @bulletin.user.name, to: Routes.user_path(@conn, :show, @bulletin.user) %>
  </li>

  <li>
    <strong>Subscribers:</strong>
    <%= length @bulletin.subscribers %>
  </li>

  <li>
    <strong>Events:</strong>
    <ul>
      <%= for event <- @bulletin.events do %>
        <li>
          <span><%= link event.title, to: Routes.event_path(@conn, :show, event) %></span>
          <span><%= event.body %></span>
          <span>(<%= event.start_date %>)</span>
        </li>
      <% end %>
    </ul>
  </li>

</ul>

<span><%= link "Back", to: Routes.bulletin_path(@conn, :index) %></span>

<%= if @current_user && @bulletin.user_id == @current_user.id do %>
<span>(
  <span><%= link "Edit", to: Routes.bulletin_path(@conn, :edit, @bulletin) %></span>
  |
  <span><%= link "Delete", to: Routes.bulletin_path(@conn, :delete, @bulletin), method: :delete, data: [confirm: "Delete #{@bulletin.title}?"] %></span>
)</span>
<% end %>

lib/notify_events_web/templates/bulletin/show_app.html.eex
<div class="flex-row flex-grow space-y-4 my-4 m-2">
<%= if length(@events) != 0 do %>
  <%= for event <- @events do %>
    <div class="pb-2 border-2 rounded-md border-black mx-auto">
      <div class="p-2 pb-1 flex justify-between bg-yellow-100 rounded-t-md">
        <h2 class="font-bold text-lg"><%= event.title %></h2>
        <h2 class=""><%= Calendar.strftime event.start_date, "%a, %b %-d %H:%M" %></h2>
        </div>
      <div class="p-2 mx-auto"><%= text_to_html event.body %></div>

      <%= if @current_user && @bulletin.user_id == @current_user.id do %>
        <p class="p-3 text-gray-600 text-right">(
          <%= link "Edit", to: Routes.event_path(@conn, :edit, event) %>
          |
          <%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Delete #{event.title}?"] %>
        )</p>
      <% end %>

    </div>
  <% end %>
<% else %>
    <div class="pb-2 border-2 rounded-md border-black mx-auto">
    <h2 class="p-2 pb-1 font-bold text-lg">No events right now... subscribe and know when something new pops up!</h2>
    </div>
<% end %>

      <%= if @current_user && @bulletin.user_id == @current_user.id do %>
      <p class="p-3 text-gray-600 text-right">(
      <%= link "New Event", to: Routes.event_path(@conn, :new, @bulletin) %>
      | <%= link "Edit Board", to: Routes.bulletin_path(@conn, :edit, @bulletin), class: "flex-grow"%>
      | <%= link "Send Notification", to: Routes.notification_path(@conn, :new, @bulletin), class: "flex-grow"%>
      )</p>
      <% end %>

</div>